import React, { useState } from 'react';
import { AnalysisResult, AnalysisSettings } from './types';
import { analyzeTranscript } from './services/geminiService';
import AnalysisForm from './components/AnalysisForm';
import ClipCard from './components/ClipCard';
import ViralChart from './components/ViralChart';
import { Sparkles, Zap, BarChart3, AlertCircle, Download, FileText, FileJson, FileSpreadsheet } from 'lucide-react';

const App: React.FC = () => {
  const [results, setResults] = useState<AnalysisResult | null>(null);
  const [currentSettings, setCurrentSettings] = useState<AnalysisSettings | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleAnalyze = async (transcript: string, settings: AnalysisSettings) => {
    setLoading(true);
    setError(null);
    setResults(null);
    setCurrentSettings(settings);

    try {
      // Use the injected API key
      const apiKey = process.env.API_KEY || '';
      if (!apiKey) {
        throw new Error("API Key not found. Please set a valid API Key.");
      }

      const data = await analyzeTranscript(apiKey, transcript, settings);
      setResults(data);
    } catch (err: any) {
      setError(err.message || "An unexpected error occurred during analysis.");
    } finally {
      setLoading(false);
    }
  };

  // --- Export Functions ---

  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const exportJSON = () => {
    if (!results) return;
    const jsonContent = JSON.stringify(results, null, 2);
    downloadFile(jsonContent, 'viral_analysis.json', 'application/json');
  };

  const exportCSV = () => {
    if (!results) return;
    const headers = ['Clip ID', 'Start Time', 'End Time', 'Viral Score', 'Category', 'Hook', 'Title', 'Risk'];
    const rows = results.clips.map(clip => [
      clip.clip_id,
      clip.start_time,
      clip.end_time,
      clip.viral_score,
      `"${clip.category.join(', ')}"`,
      `"${clip.on_screen_hook.replace(/"/g, '""')}"`,
      `"${clip.video_title.replace(/"/g, '""')}"`,
      clip.monetization_risk
    ]);
    const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    downloadFile(csvContent, 'viral_analysis.csv', 'text/csv');
  };

  const exportTXT = () => {
    if (!results) return;
    let content = `VIRAL ANALYSIS REPORT\n`;
    content += `Generated by ViralCut AI\n`;
    content += `Summary: ${results.summary}\n\n`;
    content += `----------------------------------------\n\n`;

    results.clips.forEach(clip => {
      content += `[Clip ${clip.clip_id}] ${clip.video_title}\n`;
      content += `Time: ${clip.start_time} - ${clip.end_time} (${clip.duration})\n`;
      content += `Score: ${clip.viral_score}/10\n`;
      content += `Hook: ${clip.on_screen_hook}\n`;
      content += `Reason: ${clip.reason}\n`;
      if (currentSettings?.sourceUrl) {
         content += `Command: yt-dlp --download-sections "*${clip.start_time}-${clip.end_time}" "${currentSettings.sourceUrl}" -o "clip_${clip.clip_id}.mp4"\n`;
      }
      content += `\n`;
    });

    downloadFile(content, 'viral_analysis.txt', 'text/plain');
  };

  return (
    <div className="min-h-screen bg-[#0f0f11] text-zinc-200 font-sans selection:bg-purple-500/30">
      
      {/* Header */}
      <header className="border-b border-zinc-800 bg-black/20 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="bg-gradient-to-tr from-purple-600 to-indigo-600 p-2 rounded-lg">
              <Zap className="text-white fill-white" size={20} />
            </div>
            <h1 className="text-xl font-bold tracking-tight text-white">
              ViralCut <span className="text-purple-500">AI</span>
            </h1>
          </div>
          <div className="flex items-center gap-4 text-xs font-medium text-zinc-500">
             <span>v2.0.0</span>
             <div className="h-4 w-px bg-zinc-800"></div>
             <span className="flex items-center gap-1 text-green-500">
               <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></span>
               System Online
             </span>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          
          {/* Left Column: Form */}
          <div className="lg:col-span-4 space-y-6">
            <AnalysisForm onAnalyze={handleAnalyze} isLoading={loading} />
            
            {/* Helper Card */}
            <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-5">
              <h3 className="text-sm font-semibold text-zinc-300 mb-2 flex items-center gap-2">
                <AlertCircle size={14} className="text-purple-400"/> Pro Tips
              </h3>
              <ul className="text-xs text-zinc-500 space-y-2 list-disc pl-4">
                <li>Paste transcripts from YouTube, Podcast output, or Premiere Pro text exports.</li>
                <li>ViralCut prioritizes high-emotion moments.</li>
                <li>Use the <strong>Source URL</strong> to get one-click download commands.</li>
              </ul>
            </div>
          </div>

          {/* Right Column: Results */}
          <div className="lg:col-span-8">
            {error && (
              <div className="bg-red-500/10 border border-red-500/20 rounded-xl p-4 text-red-400 text-sm flex items-center gap-3 animate-fade-in mb-6">
                <AlertCircle size={18} />
                {error}
              </div>
            )}

            {!results && !loading && !error && (
              <div className="h-full flex flex-col items-center justify-center text-zinc-600 py-20 border-2 border-dashed border-zinc-800 rounded-3xl bg-zinc-900/20">
                <BarChart3 size={48} className="mb-4 opacity-50" />
                <p className="text-sm font-medium">Ready to analyze content</p>
                <p className="text-xs mt-1">Paste a transcript to begin extraction</p>
              </div>
            )}

            {loading && (
              <div className="flex flex-col items-center justify-center py-32 space-y-6">
                 <div className="relative w-20 h-20">
                    <div className="absolute inset-0 border-4 border-zinc-800 rounded-full"></div>
                    <div className="absolute inset-0 border-4 border-purple-500 border-t-transparent rounded-full animate-spin"></div>
                 </div>
                 <p className="text-zinc-400 animate-pulse text-sm tracking-wider">READING TRANSCRIPT & SCORING MOMENTS...</p>
              </div>
            )}

            {results && (
              <div className="space-y-8 animate-fade-in-up">
                
                {/* Summary Section */}
                <div className="bg-gradient-to-r from-zinc-900 to-zinc-900/50 border border-zinc-800 rounded-2xl p-6 relative overflow-hidden group">
                  <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                    <Sparkles size={100} />
                  </div>
                  <h2 className="text-lg font-bold text-white mb-2 flex items-center gap-2">
                    <Sparkles className="text-purple-400" size={18} /> 
                    Content Summary
                  </h2>
                  <p className="text-zinc-400 leading-relaxed text-sm max-w-2xl">
                    {results.summary}
                  </p>
                </div>

                {/* Export Toolbar */}
                <div className="flex items-center justify-between bg-zinc-900 border border-zinc-800 rounded-xl p-3">
                  <span className="text-xs font-semibold text-zinc-500 uppercase tracking-wider ml-2">Export Data</span>
                  <div className="flex gap-2">
                    <button onClick={exportJSON} className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-xs text-zinc-300 transition-colors">
                      <FileJson size={14} /> JSON
                    </button>
                    <button onClick={exportCSV} className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-xs text-zinc-300 transition-colors">
                      <FileSpreadsheet size={14} /> CSV
                    </button>
                    <button onClick={exportTXT} className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-xs text-zinc-300 transition-colors">
                      <FileText size={14} /> TXT
                    </button>
                  </div>
                </div>

                {/* Chart */}
                <ViralChart clips={results.clips} />

                {/* Clips Grid */}
                <div>
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-lg font-bold text-white">
                      Identified Viral Clips 
                      <span className="ml-2 text-sm font-normal text-zinc-500 bg-zinc-900 px-2 py-0.5 rounded-full border border-zinc-800">
                        {results.clips.length} found
                      </span>
                    </h3>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {results.clips.map((clip) => (
                      <ClipCard 
                        key={clip.clip_id} 
                        clip={clip} 
                        sourceUrl={currentSettings?.sourceUrl} 
                      />
                    ))}
                  </div>
                </div>

              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
};

export default App;